FROM python:3.12-slim

WORKDIR /app

# copy app files
COPY . .

# copy entrypoint explicitly (last, to avoid overwrite issues)
COPY entrypoint.sh /entrypoint.sh

RUN apt-get update && apt-get install -y default-mysql-client && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x /entrypoint.sh
EXPOSE 5000

ENTRYPOINT ["sh", "/entrypoint.sh"]
